#!/usr/bin/env python
# -*- encoding: utf8 -*-
#
# Spotify-Notify - Notifications and media keys support for Spotify
# Copyleft (C) 2011 Victor Koronen and contributors
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

__author__ = 'Victor Koronen'
__copyright__ = 'Copyleft (C) 2011 Victor Koronen and contributors'
__version__ = '0.1'

# import standard libraries
import os, time, sys, datetime, string, re, signal
import urllib2
import pynotify
import tempfile
import webbrowser
import logging

# import custom libraries
sys.path.append(os.path.join(os.getcwd(), 'lib'))
import pylast
from daemon import Daemon

# set constants
LOG_LEVEL = logging.DEBUG
LOG_FILE_NAME = os.path.expanduser('~/.spotify-notify-daemon.log')
PID_FILE_NAME = os.path.expanduser('~/.spotify-notify-daemon.pid')
#CONF_FILE_NAME = os.path.expanduser('~/.spotify-notify-daemonrc')

CURRENT_DIR = os.path.join(os.path.abspath(os.curdir), '')
TMP_DIR = os.path.join(tempfile.gettempdir(), '')

SPOTIFY_OPEN_URL = 'http://open.spotify.com/track/'
LASTFM_API_KEY = '73f8547fa82ecbd0d0313f063c29571d' #spotify-notify's Last.fm API key

#
# The notification daemon
#
class SpotifyNotifyDaemon(Daemon):
    def __init__(self):
        # init daemon
        super(SpotifyNotifyDaemon, self).__init__(PID_FILE_NAME)

        # initialize fields
        self.old_meta = None
        self.old_id = None
        self.cover_image = None

        # setup logger
        logging.basicConfig(filename = LOG_FILE_NAME, level = LOG_LEVEL)

# TODO: handle SIGTERM
#        # catch sigterm
#        signal.signal(signal.SIGTERM, signal_handler)
#
#    def signal_handler(signum, frame):
#        print('Signal handler called with signal %d %d'.format(signum, signal.SIGTERM))

    def run(self):
        logging.info('Starting up')

        # choose backend
        try:
            import spotify_notify_dbus
            self.backend = spotify_notify_dbus.SpotifyDBus(self)
        except:
            import spotify_notify_xlib
            self.backend = spotify_notify_xlib.SpotifyXLib(self)

        # indicate init
        try:
            logging.debug('Initializing indicator applet')
            import indicate
            indicateserver = indicate.indicate_server_ref_default()
            indicateserver.set_type('music.spotify')
            indicateserver.set_desktop_file('/usr/share/applications/spotify.desktop')
            indicateserver.show()
        except:
            logging.error('Cannot initialize indicator applet')

        # loop!
        logging.debug('Entering main backend loop')
        self.backend.loop()

    """ On delete, clean up tmp cover image (if any) """
    def __del__(self):
        logging.info('Shutting down')
        logging.debug('Cleaning up cover image (if any)')
        if self.cover_image and os.path.exists(self.cover_image):
            os.unlink(self.cover_image)

    def fetchLastFmAlbumCover(self, artist, title, album = None):
        logging.debug('Fetching cover for {0} - {1} from Last.FM'.format(artist, title))
        try:
            network = pylast.get_lastfm_network(api_key = LASTFM_API_KEY)

            if (album is None):
                track = network.get_track(artist, title)
                album = track.get_album()
            else:
                album = network.get_album(artist, album)

            url = album.get_cover_image(size = 1) #Equals medium size (best speed/quality compromise)
            self.albumname = album.get_name()
            coverfile = urllib2.urlopen(url)

            # Remove old tmp if any
            if self.cover_image and os.path.exists(self.cover_image):
                os.unlink(self.cover_image)

            output = tempfile.NamedTemporaryFile(prefix="spotifynotify_cover", suffix=".jpg",delete=False)
            output.write(coverfile.read())
            output.close()
            release_date = album.get_release_date()
            if (release_date): #Lousy check, needs to be fixed in case last.fm changes date data
                release_string = release_date.split(" ")[2]
                release_string = release_string.split(",")[0]
                release_string = " ("+release_string+")"
            else:
                release_string = ""
            self.release_string = release_string
            #self.cover_image = TMP_DIR + 'spotifynotify_cover.jpg'
            self.cover_image = output.name
        except Exception as e:
            #print "Exception: ", e
            #print "Couldn't find song/cover in music database, using default image..."
            self.albumname = self.release_string =  ""
            self.cover_image = None

    def fetchCoverImageSpotify(self, trackid):
        logging.debug('Fetching cover for {0} from Spotify'.format(trackid))
        try:
            url = SPOTIFY_OPEN_URL + trackid
            tracksite = urllib2.urlopen(url).read()
            matchobject = re.search('/image/(.*)" alt', tracksite)
            imageurl = "http://open.spotify.com/image/" + matchobject.group(1)
            if not (imageurl):
                #print "No cover available"
                raise()
            coverfile = urllib2.urlopen(imageurl)
            (fd, self.tmpfilename) = tempfile.mkstemp()
            self.tmpfile = os.fdopen(fd, 'wb')
            data = coverfile.read()
            self.tmpfile.write(data)
            self.tmpfile.close()
            self.cover_image = self.tmpfilename
            return 1
        except Exception as e:
            #print "Couldn't fetch cover image"
            #print e
            self.cover_image = None
            return 0 

    """ called on track change """
    def on_track_change(self, meta):
        logging.debug('Track change handler triggered')
        # check if it really was a track change
        if meta != self.old_meta and meta is not None:
            logging.debug('Detected new track')

            # old meta is now new meta
            self.old_meta = meta

            # hack to see if there is any metadata in meta
            if 'artist' in meta:
                artist = meta['artist'] if 'artist' in meta else '(no artist)'
                title = meta['title'] if 'title' in meta else '(no title)'
                album = meta['album'] if 'album' in meta else '(no album)'
                created = meta['created'] if 'created' in meta else '0000-00-00 00:00 UTC'
                year = int(created[:4])
                track_id = meta['track_id'] if 'track_id' in meta else None
                
                #TODO: enable choise
                #coverData = self.fetchLastFmAlbumCover(artist, title, album)
                self.fetchCoverImageSpotify(track_id)

                # use cover image if available, otherwise just use the logo
                if self.cover_image:
                    cover_image = self.cover_image
                else:
                    cover_image = CURRENT_DIR + 'icon_spotify.png'

                # create notification
                n = pynotify.Notification(title, '<i>%s</i>\n%s (%04d)' % (artist, album, year), cover_image)

                # save notification id to replace popups
                if self.old_id is not None:
                    n.props.id = self.old_id

                # show the notification
                n.show()
                self.old_id = n.props.id

""" main (duh!) """
def main():
    # dependency check
    if not pynotify.init('icon-summary-body'):
        #print 'You need to have a working pynotify-library installed.\nIf you are using Ubuntu, try "sudo apt-get install python-notify"'
        sys.exit(1)

    # manage daemon
    snd = SpotifyNotifyDaemon()
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            snd.start()
        elif 'stop' == sys.argv[1]:
            snd.stop()
        elif 'restart' == sys.argv[1]:
            snd.restart()
        else:
            print('Unknown command')
            sys.exit(2)
        sys.exit(0)
    else:
        print('usage: %s start|stop|restart'.format(sys.argv[0]))
        sys.exit(2)

if __name__ == '__main__':
    main()

